//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashBoxModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CashBoxDBContext : DbContext
    {
        public CashBoxDBContext()
            : base("name=CashBoxDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<HairColour> HairColour { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<Height> Height { get; set; }
        public virtual DbSet<Weight> Weight { get; set; }
    }
}
