//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashBoxModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "{0} is required")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "{0} is required")]
        public string Surname { get; set; }
        [Required(ErrorMessage = "{0} is required")]
        public System.DateTime DateOfBirth { get; set; }
        [Required(ErrorMessage = "{0} is required")]
        public string Address { get; set; }
        [Required(ErrorMessage = "{0} is required")]
        public string Email { get; set; }
        [Required(ErrorMessage = "{0} is required")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "{0} is required")]
        public string Status { get; set; }
        [Required(ErrorMessage = "{0} is required")]
        public string Password { get; set; }
        public System.DateTime DateCreated { get; set; }
        [Required(ErrorMessage = "{0} is required")]
        public string Image { get; set; }
        public bool Deleted { get; set; }
    }
}
