//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashBoxModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Weight
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "{0} is required")]
        public double WeightValue { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
